rstudio/bookdown

inst/templates/gitbook.html
This change fixes a problem wherein the header scrolled with the body when the page is < 600px. 
The problem is somewhat subtle: at < 600px, CSS translations are used to shift the body contents to the left to accommodate the sidebar (this happens near the end of the minified `style.css`). Unfortunately, a side effect of using CSS transforms such as translations is that they unstick fixed content (i.e. they operate on all nested elements, even if those elements were formerly positioned relative to something else.) 
The fix here is to override the translations applied by the stylesheet, and to use ordinary CSS positioning properties at < 600px to lay out the columns.
=> Position header/body without translations at < 600px

R/publish.R, man/publish_book.Rd
- Support for automatic updating of existing deployments with no arguments to publish_book (i.e. inherit the name, account, and server of the previous deployment so long as there is only one)
- Provide option to render book before publishing. This defaults to FALSE but can default to TRUE via the setting of a global bookdown option (this is for users that want to always render before publishing and don't want to have to remember to pass render = TRUE)
=> Improvements to publish_book

inst/resources/gitbook/js/plugin-bookdown.js
- I've now put in a fix that makes 'unload' work properly in the external preview window. I also noticed that 'blur' doesn't work for some situations (i.e. manually refreshing in the preview window)
- The window.location.hash doesn't seem to have the desired effect. I think it's on RStudio to NOT do the hash restoration in the first place here.
=> remove rstudio preview tweaks

DESCRIPTION, R/publish.R, man/publish_book.Rd
We have now made all of the functionality formerly provided by `publish_book` generic for all types of websites (via the `rmarkdown::site_generator` mechanism). As a result, `publish_book` can now just delegate to `rsconnect::deploySite`. 
Users could now simply call `rsconnect::deploySite` rather than `publish_book`, however the latter includes automatic provisioning of an account on bookdown.org which is a nice simplification of workflow. If the think that this doesn't justify having our own function though we could simply dispense with `publish_book` entirely.
=> Use rsconnect::deploySite for publish_book

R/site.R
If a single file is passed to rmarkdown::render_site then this file is forwarded to the generator's render function as 'input_file'. This currently occurs when the IDE processes a "Knit" for a file within a website so we turn this into a single chapter preview.
Note that with this change knit: bookdown::preview_chapter will no longer be necessary to get single-file incremental preview in the IDE (this change should be in tomorrow's daily build of the IDE).
=> accept input_file argument to site_generator$render

R/render.R, R/site.R
There is a new `clean` function which site generators must implement. It returns a site-relative list of files that should be cleaned (the `clean_site` wrapper function is the one that actually does the removal when the `preview` argument to `clean_site` is FALSE.
I was able to re-use the existing `clean_book` function by just arranging for it to return the `out` vector for `clean = FALSE`.
=> implement rmarkdown site generator clean function

inst/resources/gitbook/css/plugin-bookdown.css
- Hide book-summary, book-header and page flick-arrows to improve HTML printing layout
- Make overflow parts visible on printing page
=> fix HTML print

.travis.yml
CI's are failing randomly because the phantomjs downloads can fail. For example, see https://travis-ci.org/rstudio/bookdown/builds/128022555
For background of the problem: https://github.com/ariya/phantomjs/issues/13953
webshot updated here: https://github.com/wch/webshot/pull/21
=> phantomjs mirror

R/word.R
When using `word_document2` to publish a *docx* document as any other format (epud, pdf, mobi), the docx document is not moved automaticallly in *output_dir*, even if it is specified in *_bookdown.yml*. 
For function, `epub_book` it works because it has a post_processor function that move the epub document in `output_dir`, as specified in *_bookdown.yml*.
I propose to add the same function to the `word_document2` function so that when we use `bookdown::word_document2` in *_output.yml* or in yaml header in *index.Rmd*, the *docx* file is moved in output dir with others. 
Moreover, that way, adding
```r
download: ["epub", "docx"]
```
in *_output.yml* for `bookdown::gitbook:` config will work without any manual operation. 
What do you think? 
However, I do not know if I had to put 
```r
post …
```
=> add post_processor to word_document2

inst/examples/05-publishing.Rmd
Using the `/docs` folder approach to publishing to gh-pages requires less steps than via a gh-pages branch.
=> Added simpler method for publishing book to gh-pages via /docs folder

inst/templates/gitbook.html
Add author affiliation in the YAML metadata block using the `institute` field. This field is available in other templates, such as in the default beamer template. See, for example, http://stackoverflow.com/a/35888123/3365410.
=> Add author affiliation

inst/examples/02-components.Rmd
Is a valid use case, and a nice way to show where to put the caption's label. (I used a test run with `keep_md = TRUE` for that purpose.)
=> Draft: Inline tables

inst/examples/05-editing.Rmd
used "refer to" in place of "see", which appears again in a couple of words in the same sentence
=> replaced "see" with "refer to"

inst/examples/02-components.Rmd
In trying to solve an [issue with using markdown in figure captions](https://github.com/yihui/knitr/issues/1334), I looked through the "Figure" section of the docs without realizing the relevant answer was hiding in the "Text references" section. This cross-reference will hopefully help other users find the answer more quickly.
=> link to Text references page from Figure captions

inst/templates/gitbook.html
Following the suggestion in https://github.com/rstudio/bookdown/issues/265, this means we can use `_output.yml` to inject text and HTML just above each chapter/section title like this:
```
bookdown::gitbook:
includes:
before_body: xxxx.html
```
=> move include-before to allow includes: before_body to put HTML on page

R/word.R
unless not passing the arguments was intended?
=> Pass along pandoc_args to rmarkdown::word_document()

R/html.R
Originally looking for `<caption>` fails to find `caption` tags that
include attributes. Allowing for attributes paves the way for using
`\@ref` syntax with custom HTML tables.
This is addresses #372
=> Modifed caption search in parse_fig_labels()

R/html.R
Prepend the value of `--id-prefix` passed to pandoc conversion in order to correctly resolve cross-references. Addresses https://github.com/rstudio/rmarkdown/issues/1063.
=> Prefix section labels in cross-references 

inst/examples/06-publishing.Rmd
Here is a 2nd try at explaining how .nojekyll fits in with the two different GitHub pages approaches.
=> add .nojekyll when doing /docs approach

R/html.R, R/latex.R
Exercise falls under the Definition category. Solution falls under the Proof category. I suspect these will be of widespread interest to authors writing activities and solutions. I was not sure how to test these changes. Considered adding an additional activity/solution example to 02-components.Rmd, but did not do so.
=> Add Exercise and Solution to included theorem/proof environments

R/latex.R
With `citation_package: biblatex` in `_output.yml` `biber` is used to process bibliographies nicely, but it leaves a `.run.xml` files lying around. This commit takes care of cleaning it up afterwards.
=> Clean up after biber

inst/examples/_output.yml
https://www.w3.org/TR/html51/browsers.html#browsing-context-names
=> replace blank with _blank in <a>

R/html.R
Before the change, multiline footnote is not handled properly.  Consider the following minimal example:
```
---
title: "A Book"
author: "Frida Gomam"
site: bookdown::bookdown_site
documentclass: book
output:
bookdown::gitbook: default
bookdown::pdf_book: default
---
Footnote test.^[Multiline
footnote
should
be
allowed]
```
Before the change, the entire footnote appears as one single word:
With the change, the footnote appears properly:
=> Fixes multiline footnote word-spacing issue.

inst/examples/03-formats.Rmd
In reference to #162 section 3.1.1. of the 'bookdown' book still uses double quotes for the 'url' YAML metadata tag. Since pandoc is apparantly still missing the feature to handle double quotes for this very tag, copying the code from the book still results in an unknown escape character error.
=> single quotes for the URL (#162)

R/html.R
The existing ordering with Proposition and Corollary after Definition causes proposition and corollary environments to pick up the style from definition when output to PDF through LaTex. Moving these ahead of Definition so that they follow immediately Theorem and Lemma will let them pick up the same theoremstyle as Theorem and Lemma which is the desired behaviour as documented in the bookdown book.
=> Changed the ordering math environments so that Proposition and Corollary get default theoremstyle

inst/examples/06-publishing.Rmd
This change brings the documentation in line with the implementation. It is important to have `\frontmatter` in `preamble.tex` and not in `before_body.tex`. Otherwise the title page would not be part of the front matter and page numbering would be reset *after* it. 
Motivated by this SO question: https://stackoverflow.com/questions/43711029/page-numbering-in-r-bookdown/
=> Document that \frontmatter goes into preamble.tex

DESCRIPTION, NEWS.md, R/utils.R, inst/examples/04-customization.Rmd
**Description:**
If `rmd_subdir` is true then bookdown searches for files *recursively* from the project root directory. If `rmd_subdir` is a list of subdirectories then bookdown search for files *recursively* from each subdirectory.
I have submitted the individual contributor agreement and welcome feedback on this pull request.
Fixes #242
=> Allow `rmd_subdir` to be either a bool or list of subdirectories.

DESCRIPTION, R/ebook.R, R/gitbook.R, man/epub_book.Rd, man/gitbook.Rd
The output only changes when the user explicitly provides a `template`. The output isn't changed when no `template` is given, making the changes backward compatible.
=> allow custom pandoc templates for gitbook and epub

R/render.R
The creation of temp files using the `tempfile()` function creates files with a path of ".\\\filename".  However, when using the `unlink `function with default of `recursive = FALSE`, these created temp files are not removed as expected.  When `recursive = TRUE` is added to the unlink function call, then it works.  Code which reproduces the problem on my machine is below:
```r
tempFile = tempfile('render', '.', '.rds')
print(tempFile)
file.exists(tempFile)  ### returns FALSE, nothing written to file
writeLines("This is a temp file", con = tempFile)
file.exists(tempFile)  ### returns TRUE
unlink(tempFile)
file.exists(tempFile)  ### returns TRUE, file still exists!
unlink(tempFile, recursive = TRUE)
file.exists(tempFile)  ### returns FALSE, finally got rid of it
```
=> Add recursive = TRUE to unlink functions in render.R

R/latex.R
the current regex is also triggered with types like "exampleblock". The new regex is only triggered with exact matches
=> make regex a bit more strict

inst/examples/index.Rmd
Error in contrib.url(repos, type) :
trying to use CRAN without setting a mirror
Calls: ... lapply -> FUN -> install.packages -> grep -> contrib.url
if without .Rprofile, the original code can pop the same error.
=> Solve error without .Rprofile

R/render.R
Currently, during rending the code copies the backs up the R markdown file to a temporary file in the same directory with the a name like `bookdown11b6326822f9c`. This file should be cleaned up, but sometimes is not if the process is killed. If the file happens to not be cleaned up, it is hard to write a globbing expression for `.gitignore` and similar to match it that and wouldn't result in false positives; `bookdown*` is the best I can come up with. I propose
1. Use a `.bak` extension to make it easier to match with globbing.
2. Use the original filename as the base, since it is backing up a particular file. If the process is killed, then it is easier to restore the original file.
Alternatively, if the backup file never needs to be restored by the user, why not put it in the temporary …
=> Change name of temporary files created.

inst/examples/04-customization.Rmd, inst/examples/06-publishing.Rmd
The pandoc argument `--chapters` was deprecated in favor of `--top-level-division=chapter`, and this change [was made](https://github.com/rstudio/bookdown/commit/90f4c8d65d7d612b9ed280fd05ec3a1bb65d25d8) for `_output.yml` but not for the content in the book. 
This PR updates the book's text to the modern pandoc argument.
For Ch.6, I chose not to enclose the argument with quotes to make it consistent with Ch.4, and also because that's how `_output.yml` does it.
=> Update deprecated pandoc_args for pdfs in book

inst/examples/css/style.css
I would use 600 instead of 500 because I can't see the difference between 500 and 400 using my notebook and others may have the same problem.
@yihui do you agree?
=> Make the strong tag more differentiable

NEWS.md, R/html.R
I've personally tested this only on a minimal example:
1. Create a new RStudio project using the bookdown template
2. Add this code chunk somewhere (e.g. bottom of index.Rmd):
```{r this will not show}
library(ggplot2)
ggplot(iris, aes(x = Petal.Length, y = Petal.Width, color = Species)) + geom_point()
```
3. Verify bug: The image doesn't show because the resource is missing (png is named "this will not show-1.png" while the src attribute is URLencoded to "this%20will%20..."
4. Install this branch and rerun
5. The image is now correctly copied and displays (in Firefox, oddly *not* in the RStudio preview browser, but that is another bug found I guess...)
=> Fix using utils::URLdecode

NEWS.md, R/utils.R
If the rstudioapi package is installed but serve_book is called outside
of RStudio `getSourceEditorContext()` would signal an error.
We now check if RStudio is available first, which fixes the issue.
=> Fix serve_book when not running in RStudio

inst/resources/gitbook/js/plugin-search.js
Appended HTML <label> to $searchForm for increased accessibility. The label will help screen readers that may not read the <input> placeholder attribute (in this case, "Type to search"). The procedure to add a <label> element alongside an <input> is suggested by Khan Academy's [tota11y accessibility tool](https://github.com/Khan/tota11y). Refer to [W3C on labels and web accessibility](https://www.w3.org/WAI/tutorials/forms/labels/).
=> Added label to search form for screen readers

DESCRIPTION, NEWS.md, R/html.R
As reported in #661, the split reference sections in `gitbook` do not respect the sorting defined in the CSL file. Instead references are always listed in the order of citations in the text of the current page. This PR ensures that the sorting in the split reference sections adheres to the CSL definition. Currently, this is hard coded. If you prefer I'd be happy to add an argument, e.g., `split_bib_sorting`, that allows selecting any of these two behaviors.
=> Retain sorting in split reference sections of gitbook as defined in CSL file

R/html.R, man/html_document2.Rd
I implemented a toggling option to the `clean_pandoc2_highlight_tags` in `html_document2` (Issue https://github.com/rstudio/bookdown/issues/705)
The toggling is achieved by specifying `highlight_cleaned` in a YAML front matter, which is `TRUE` in default for consistency with previous versions.
If there is any better name for this option, please tell me.
Here's a reproducible example.
````
---
output:
bookdown::html_document2:
highlight: pygments
highlight_cleaned: false
---
```{r, class.source = "numberLines lineAnchors", eval = FALSE}
head(iris)
```
````
=> feat: toggle clean_pandoc2_highlight_tags in html_document2

NEWS.md, inst/templates/default.html, inst/templates/gitbook.html
add Pandoc's variable $abstract-title$, so allow user to custom abstract title when output is bookdown::gitbook
see https://d.cosx.org/d/420658 for feature discuss
=> allow user to custom abstract title when output is bookdown::gitbook

inst/examples/03-formats.Rmd
This will close #752 by adding a piece in documentation book about using `word_document2` in `_output.yml`
@bblodfon, do you find it clearer if we add these lines ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rstudio/bookdown/759)
=> add an example to output a book in word document

NEWS.md, R/gitbook.R
This will fix #739 using by using the same regex mechanism as of now. (See discussion in the issue)
See PR is a joint effort with @RLesur, Thanks Romain ! 
As explained in the discussion, Pandoc 2 changed the way it creates self contained document. JS script are now included inside `<script>` html tags no more base64 encoded by default. 
See https://github.com/rstudio/bookdown/issues/739#issuecomment-541349632
This means that bookdown must look for encoded and not encoded script html node. Also, it must look for possible multiline blocks and not single line html node.
This PR makes bookdown post processing compatible with all pandoc version by : 
* Modifying the regex to look for encoded and not encoded JS script
* deal with multiline blocks beginning with `<script>` and finishing with …
=> Add compatibility with new pandoc2 way of creating self contained document

NEWS.md, R/html.R
This fixes #793 
There was a change in pandoc where  the ⤶︎ was previously a single unicode `\u2936`, and now it is encoded in two unicode character `\u2936\uFE0E`. That breaks the regex that identify footnootes in html code. In regex, a dot `.` will only match one unicode, not two even if it is one. 
See example: 
``` r
grep(">.</a>", enc2utf8(">\u2936</a>"), value = TRUE)
#> [1] "><U+2936></a>"
grep(">.</a>", enc2utf8(">\u2936\uFE0E</a>"), value = TRUE)
#> character(0)
grep(">.+</a>", enc2utf8(">\u2936\uFE0E</a>"), value = TRUE)
#> [1] "><U+2936><U+FE0E></a>"
```
This is an easy fix to use `.+` instead of `.` - I used that for now.
This can also be handled using purl regex and special pattern `\X`. See [here](https://www.regular-expressions.info/unicode.html)
``` r
grep(">\\X</a>", …
```
=> handle change in footnotes from pandoc 2.7.3

NEWS.md, R/html.R, tests/rmd/parse-footnotes.Rmd, tests/test-rmd.R
This complete the fix for #793 that was previously handled in #798 
The regex was not correct. I am really sorry for the quick fix that was not correct. handling html with regex is not a trivial task.
Instead, this time to be sure I propose to use the other method I find more robust : match exactly for a unicode char using perl regex and special pattern `\\X`. 
This will get correctly a named vectors of footnotes, with correct names so that relocation happens correctly even in special case (this closes #799)
It is difficult to really test completly the impact of those changes. 
@yihui , I am really sorry to PR some changes that are not fully vetted and properly tested. 
I think this one is now ok. I tested again the example in #799, with pandoc 2.7.2 and pandoc 2.7.3.
<details> <summary> …
=> Correct fix for footnote unicode change in pandoc 2.7.3

NEWS.md, R/gitbook.R, inst/examples/03-formats.Rmd, inst/resources/gitbook/js/plugin-sharing.js
This closes #797 
As explained in https://github.com/rstudio/bookdown/issues/797#issuecomment-549181261 there was changes in sharing url. 
This PR: 
* removes google+ as it does not exist anymore. 
* updates sharing link for twitter and facebook
* changes icon for instapaper as `fa-instapaper` does not exists.
`fa-italic`
Instapaper icone 
Google sharing is removed from example and default value. 
A new function `check_gb_config` is here to check configuration and change user's config with a warning to disable some option. (here remove google from `sharing` list or `all` vector
I think this is enough to not break older bookdown where `google` would have been present in configuration. 
We could also leave as is and the sharing link would redirect to google+ removal page …
=> Update sharing urls

DESCRIPTION, NEWS.md, R/gitbook.R, R/html.R, inst/examples/03-formats.Rmd, inst/examples/04-customization.Rmd, inst/resources/gitbook/js/plugin-bookdown.js
This closes #805. I followed the model of pull request #639 Add option for a `history` button.
=> add a view button to gitbook toolbar

NEWS.md, inst/resources/gitbook/js/plugin-bookdown.js
This will fix #819 
When there is some special characters (like accentuated ones) in chapter titles, the default `split_by: chapter` will create several html file with the a name like the chapter title. 
Example from bookdown demo: 
* `litérature.html` in French if you put `# Litérature` in file `02-literature.Rmd`
In this case, as described in #819, there is an issue in the TOC. This is because 
https://github.com/rstudio/bookdown/blob/cc9dcecbfe510ea01eefc8d8651662b9164fb25b/inst/resources/gitbook/js/plugin-bookdown.js#L98-L99
will get you url encode filename
```js
var href = window.location.pathname;
href = href.substr(href.lastIndexOf('/') + 1);
href
> "lit%C3%A9rature.html"
```
All the JS logic afterward is broken because it will compare this href with some attributes and even use it …
=> TOC collapse by section works with accents in chapter html filename

NEWS.md, R/word.R
* This PR makes it easier for those who use similar approach mentioned in #782.
* Added `github_document2` on top of `rmarkdown::github_document`.
* Reordered functions in `R/word.R` alphabetically.
The following works without any issues:
````
---
output: bookdown::github_document2
---
See Table\ \@ref(tab:test-table).
```{r test-table}
knitr::kable(head(airquality), caption = "Test table.")
```
---
See Figure \@ref(fig:test-figure).
```{r test-figure, fig.cap="Figure test."}
hist(airquality$Ozone, col="blue")
```
````
=> Added github_document2

NEWS.md, R/html.R, tests/rmd/split-section.Rmd, tests/test-rmd.R
This will fixes #787 
To understand what does not work currently, here is a `index.Rmd` to reproduce
````r
---
title: "My book"
site: bookdown::bookdown_site
output:
bookdown::gitbook: 
split_by: "section"
---
| Target | Label |
| ------ | ----- |
| Chapter 1 | \@ref(chapter-1) |
| Section 1.1 | \@ref(s:1:1) |
```{r iris-plot, fig.cap="A plot"}
plot(iris)
```
See figure \@ref(fig:iris-plot)
````
When using `split_by: sections` , a _h2_ following a _h1_ with no content in between will broke the section reference, and will create an incorrect number in figure reference. 
You'll get a 
```r
Warning message:
The label(s) chapter-1 not found
```
This is because bookdown processing will add a closing `div` tag, to support special bookdown feature, when `split_by`  is `section` or …
=> Fix cross referencing when spliting by sections

NEWS.md, R/utils.R, tests/testit/test-utils.R
This will fix #857 
Currently in `render_book`, when `output_dir = "."`, it will be set internally to `NULL` as bookdown will ignore it in several places
https://github.com/rstudio/bookdown/blob/581bb639b273a5872e01c10d382065a80a641bf0/R/utils.R#L82-L94
Currently, `clean_empty_dir` throws an error when `output_dir` is NULL
https://github.com/rstudio/bookdown/blob/581bb639b273a5872e01c10d382065a80a641bf0/R/render.R#L78-L79
With this PR, `clean_empty_dir` will also ignore `output_dir = NULL`as the current working directory will not be empty and we don't want to remove it anyway. 
From my understanding, `dir` could be NULL for `clean_empty_dir` only in this special case, as otherwise `output_dirname()` will have resolved differently.
This PR also adds tests for this utils function.
=> ignore a NULL output_dir when cleaning empty directory

DESCRIPTION, NEWS.md, R/word.R
I have confirmed the following works without any issues:
`test.Rmd`:
````
---
output: bookdown::context_document2
---
```{r test, echo=FALSE}
library(knitr)
```
See Table\ \@ref(tab:test-table).
```{r test-table}
knitr::kable(head(airquality), caption = "Test table.")
```
---
See Figure \@ref(fig:test-figure).
```{r test-figure, fig.cap="Figure test."}
hist(airquality$Ozone, col="blue")
```
````
=> Added context_document2

NEWS.md, R/html.R, tests/rmd/parse-footnotes.Rmd, tests/test-rmd.R
This fixes #840 
Newline character was not correctly parsed in the regex pattern as by default in PCRE a dot matches all except newline character. Adding the modifier changes this.
=> Multiline footnote are now correctly parsed again

NEWS.md, R/utils.R, tests/testit/test-utils.R
This fixes #885 and follows a series of features addition for `source_files` (#561, #601) in the past. 
There was still an issue when `rmd_files` is provided with `rmd_subdir` due to the following behavior: 
when `rmd_subdir` was provided, all the files from root dir and subdirs were selected. `rmd_files` was not able to filter out the desired root files. 
This PR will identify subdir files apart from root files if `rmd_subdir` is provided, then if `rmd_files` is provided also, it will concatenate `rmd_files` with `rmd_subdir` content only, discarding any other root files content. 
This PR also add tests so that all the desired behavior are checked: 
* by default, only root files are selected apart from ignored files (starting with `_`)
* `rmd_files` allows to select the root files and …
=> correcly get source files when rmd_files and rmd_subdir are provided

inst/resources/gitbook/js/plugin-bookdown.js
In this Stackoverflow question, a minimal `bookdown::gitbook` document is created:  https://stackoverflow.com/q/62489019/2554330.  When viewing the result of the document in RStudio's previewer, I see this in the Javascript console:
```
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
at plugin-bookdown.js:152
at Object.<anonymous> (plugin-bookdown.js:191)
at Object.dispatch (jquery.min.js:3)
at Object.r.handle (jquery.min.js:3)
at Object.trigger (jquery.min.js:4)
at Object.<anonymous> (jquery.min.js:4)
at Function.each (jquery.min.js:2)
at n.fn.init.each (jquery.min.js:2)
at n.fn.init.trigger (jquery.min.js:4)
at Object.start (app.min.js:1)
```
This happens because in that minimal document, `li[0]` is undefined.  The PR puts in a sanity check.  (There's a …
=> Minor fix for bookdown::gitbook

NEWS.md, R/utils.R
The `--file-scope` behavior introduced in bookdown v0.20 is now disabled by default. This is due to broken TOC links for duplicate section names (e.g. "Exercises") that have automatically generated identifiers.
Addresses https://github.com/rstudio/bookdown/issues/909
=> Disable pandoc --file-scope by default

DESCRIPTION, NEWS.md, R/word.R, man/html_document2.Rd, tests/rmd/number-sections.Rmd, tests/test-rmd.R
Please merge after https://github.com/rstudio/rmarkdown/pull/1879
This PR adds number_sections argument to `markdown_document2` and its family (e.g., `word_document2`).
I set `TRUE` as a default value to be consistent with other formats (e.g., `html_document2`).
However, this may not be a good idea in case users' Rmd files manually numbered sections...
=> add number_sections argument to markdown_document2 (closes #756)

inst/examples/03-formats.Rmd
As it is seems it was not obvious
https://community.rstudio.com/t/how-to-make-bookdown-dark-mode-by-default/83375/2
=> Add an example for fontsettings config in the book

NEWS.md, R/utils.R
This fixes the dependency for --metadata-file to be on pandoc >= 2.3 (where it was introduced)
Closes #979
Signed-off-by: Mark Hymers <mark@hymers.org.uk>
=> Fix pandoc version dependency for --metadata-file

NEWS.md, R/render.R
Remove input Rmd file's path in opts could bring inconsistency.
For example in `split_chapter()`, we compare `input_rmd` and `nms_chaps`
to determine if we could skip writing html. Then when we call
`serve_book()`, all the changed Rmd files under subdir will be ignored
due to the absence of `input_rmd`'s full path.
This is the root cause of #834.
Making this change at the `opts$set` part leaves us more freedom.
We can use `basename` to trim the path later if necessary.
On the other hand, it's not easy to recover the original path info.
=> fix #834: preserve input Rmd's origin path in opts

DESCRIPTION, NEWS.md, R/html.R, R/utils.R
This fixes #976 by modifying the regex to parse the references in HTML. 
Previously we had:
```html
<div id="refs" class="references">
<div id="ref-xie2015">
<p>Xie, Yihui. 2015. <em>Dynamic Documents with R and Knitr</em>. 2nd ed. Boca Raton, Florida: Chapman; Hall/CRC. <a href="http://yihui.name/knitr/">http://yihui.name/knitr/</a>.</p>
</div>
<div id="ref-R-bookdown">
<p>———. 2020. <em>Bookdown: Authoring Books and Technical Documents with R Markdown</em>. <a href="https://github.com/rstudio/bookdown">https://github.com/rstudio/bookdown</a>.</p>
</div>
</div>
```
and now 
```html
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-xie2015" class="csl-entry">
Xie, Yihui. 2015. <em>Dynamic Documents with <span>R</span> and Knitr</em>. 2nd ed. Boca Raton, Florida: …
```
=> Correctly relocate references with Pandoc 2.11

inst/templates/gitbook.html
Adds the slash no matter what. If trailing slash is already there, the complete URI of the cover image will simply have an extra slash, which should be fine.
=> Allow "url" to work with or without trailing /

NEWS.md, R/html.R
fixes #991
We also match single quote with this regex. 
Checking:
``` r
z <- c("url(truetype/Spectral-ExtraLight.ttf)",
"url(\"truetype/Spectral-ExtraLight.ttf\")",
"url('truetype/Spectral-ExtraLight.ttf')",
"dummy line")
r = 'url\\((?:"|\')?([^")\']+)(?:"|\')?\\)'
regmatches(z, regexec(r, z))
#> [[1]]
#> [1] "url(truetype/Spectral-ExtraLight.ttf)"
#> [2] "truetype/Spectral-ExtraLight.ttf"     
#> 
#> [[2]]
#> [1] "url(\"truetype/Spectral-ExtraLight.ttf\")"
#> [2] "truetype/Spectral-ExtraLight.ttf"         
#> 
#> [[3]]
#> [1] "url('truetype/Spectral-ExtraLight.ttf')"
#> [2] "truetype/Spectral-ExtraLight.ttf"       
#> 
#> [[4]]
#> character(0)
```
@yihui I left `regexpr` + `gsub`, but this is definitly a use case for `regexec`
@RLesur can you try with this PR ?
=> Also match url with single quote when identifying resources to move.

DESCRIPTION, NEWS.md, R/render.R
This will fix #1003 by modifying the fix of #834 done in #955 
The previous fix was ok for `serve_book` and subdirectories, but it broke some stuff (that we did not see... hard to test also currently)
Removing `basename` was way to agressive because sometimes absolute path can be pass as `input` (ex. in `render_site`). 
All **bookdown** filename comparaison are with relative path - so having an absolute path in `opt$get('input_rmd')` was breaking everything that needs a relative path. 
This new fix use `xfun::relative_path` based on the current working dir that `render_book` is running from. 
This should fix the subdirectory issue while not breaking the preview feature. 
cc @shenfei as I modified your initial fix.
=> Fix preview of Rmd file 

R/render.R, man/render_book.Rd
This will close #989 
Currently 
* `input` has no default value, but when it is not provided (i.e `render_book()` only), it will error. 
* `render_book` will assume it is run from the book project directory which is the working dir. One must use 
```r
xfun::in_dir("inst/examples", bookdown::render_book("index.Rmd"))
```
from the bookdown project for example 
This PR adds the ability to provide a directory to `render_book` (as is `serve_book`) and in that case it will use `index.Rmd` in that directory if it exists. 
* New default for `input` is current working directory, so `index.Rmd` will be used if it exists. 
* If a directory is provided, working is changed for that directory for the rendering (like in `serve_book`)
* There was not much assertation on that `input` argument so I added …
=> Add default behavior for input in render_book by supporting a directory

NEWS.md, R/render.R, R/utils.R, tests/testit/test-utils.R
To handle several inputs in `render_book(input=)`. Currently it seems to work but we have warnings thrown in `xfun::relative_path`
```r
Warning messages:
1: In if ((n1 <- nchar(p)) == 0) return(x) :
the condition has length > 1 and only the first element will be used
2: In if (is_sub_path(p, d, n2)) { :
the condition has length > 1 and only the first element will be used
3: In if (p2 == "") p2 = "." :
the condition has length > 1 and only the first element will be used
```
Reported in #1090 
Other solution would be to make `xfun` functions vectorized. @yihui would that be better ? 
This type of situation make me feels we are trying to recreate / maintain / tests some functionality we could get elsewhere : **fs** package is rather low level with no dependency and could help power all the …
=> Add a vectorized wrapper for xfun::relative_path

NEWS.md, inst/templates/gitbook.html
Not a huge problem, but the nesting of authors and affiliations gets mangled due to misplace $endif$.  Also added some css styling in these cases to separate the author affiliations.  Attached is a screenshot of what the styling effects are.
=> Fix nesting of multiple authors/affiliations in gitbook.html template.  Add conditional styling

NEWS.md, inst/templates/gitbook.html
By moving the CSS inline we keep the style changes without the CSS.  This can be changed with CSS override by users - see [here](https://css-tricks.com/override-inline-styles-with-css/).
The proposed changes result in the following output:
=> Move css to inline HTML style. CSS ineffective without #header.

NEWS.md, R/latex.R, tests/testit/test-latex.R
This will close #450 and also fixed `toc_bib` that was no more working because of indentation in tex template. 
Basically, natbib and biblatex does not include the same syntax. See Pandoc's template: https://github.com/jgm/pandoc/blob/master/data/templates/default.latex
which was explained in the issue.
Also, the trick for natbib does not work for bibtex. We need to use another syntax. 
I choose to modify the tex line with regex to add the option `heading=bibintoc`.
Other solution would have been to add `\DeclarePrintbibliographyDefaults{heading=bibintoc}` in preamble. This seems more complicated from within `add_toc_bib()` function and it works only with recent biblatex (https://tex.stackexchange.com/a/544718/209358)
I added test that help me fix already some edge cases.
I tested …
=> toc_bib works with biblatex

NEWS.md, R/html.R
This PR solves #952 by modifying the order in which looking for the targets ids. 
1. We first gets href= in <a> targets to retrieve relevant footnote
2. We then rerun the function to get href in body + relocated footnote
3. We use the full identified ids to find the references and append to body
4. we rerun footnote relocation so that footnotes are appended after references
Tested with the reproducible example given: https://github.com/jimhshen/citationfootnotes
=> Also parse references in footnotes

DESCRIPTION, NEWS.md, R/ebook.R, R/html.R, R/latex.R, R/utils.R, inst/examples/04-customization.Rmd, tests/testit/test-html.R
This will solves #1114 
For now I only added support for `fig`, `eq` and `tab`. Support for theorem or proof env is a bit trickier because `label_prefix` is used for find the label to use for `\newtheorem` in `preamble` where number is not used
https://github.com/rstudio/bookdown/blob/cec8efb9cc695d4c8e873f828abe9e171bd5d50e/R/latex.R#L239
and for proof env too
https://github.com/rstudio/bookdown/blob/cec8efb9cc695d4c8e873f828abe9e171bd5d50e/R/latex.R#L248
This means it can't be a function of reference number, and case is different between LaTeX and non LaTeX. 
I wanted to support all because for non LaTeX output this is the same mechanism: label is prepended by default. However, I did not find an easy way to do it because of the constraint mention above. But also I am not sure that what …
=> Allow use of a function for fig, eq or tab labels

NEWS.md, R/site.R, tests/testit/test-site.R
fixes #1121 
It is like with **blogdown**, with this adjustment a Rmd file in a subdir can be previewed using the knit button. 
Only issue is that RStudio IDE won't open the preview because 
* `rmarkdown::render()` returns a relative path e.g `_book/02-litterature.html` to the bookdown project
* RStudio IDE consider a relative path as being relative to the input file - which in this case is not because the Rmd file is in a sub directory. 
Rmarkdown website deals with that by suppressing message for `render()` to avoid `Output created:` to be written by `render` in console and throw itself the message with `render_site()` - this happens in `default_site()`. 
I tried adding one message in `render=` inside `bookdown_site()` but as `render()` already emits one, only the first is taken into …
=> Allow the knit button to work in subdirs

inst/templates/default.html
I think #969 should have included this change as well, to make both templates work the same way with cover images.
=> bring default.html in line with gitbook.html template

.Rbuildignore, DESCRIPTION, NEWS.md, R/latex.R, inst/rmarkdown/lua/custom-environment.lua, tests/manual/.gitignore, tests/manual/README.md, tests/manual/theorem-proof-engine.Rmd, tests/manual/theorem-proof-fenced.Rmd, tests/rmd/custom-environments.Rmd
This PR closes #1143 
After all I think it is best the **bookdown** does not interfere with _beamer_. _beamer_ defines its [own theorem env](https://github.com/josephwright/beamer/blob/56b5d77a5b1ad886f452f23148b0e2e36094c689/base/beamerbasetheorems.sty#L114) with some not supported by **bookdown**. So it would be lead to have a specific syntax for some env supported by **bookdown** and another syntax for other 
````markdown
::: {.lemma name="my name"}
`lemma` is known by bookdown
:::
::: {.fact data-latex='[Special]'}
fact is not known but define by beamer. It would only work in beamer.
:::
```` 
If we don't process beamer output, this means that the syntax is 
````markdown
::: {.lemma data-latex="[my name]"}
Using `data-latex` works also as `latex`
:::
::: {.fact data-latex='[Special]'} …
```
=> Improve usage of fenced divs for Theorem and Proof environment 

R/render.R, man/render_book.Rd
`render_book("index.Rmd",  "pdf_book")` gives an error when ran. According to https://bookdown.org/yihui/rmarkdown/output-formats.html and rstudio/bookdown#585 the output format must specify the bookdown package, which does run correctly.
=> Fix error in render_book() example

inst/examples/02-components.Rmd
This close #939 (I used the incorrect number in other PR #1173)
I thought about this and decided that it was not a good idea to re-document custom block in this book. It would be a duplication in two places. 
So I added a box to mention that the `block` and `bloc2` engine are no more to be used and one should look at the R Markdown Cookbook
Is that enough ? 
We could later just remove this chapter from **bookdown** for a second edition as there would not be any specificity.
=> [DOCS] Add a box about new custom block syntax in the cookbook

inst/examples/02-components.Rmd
closes #1169 (and other related issues)
This modifies the documentation about Theorem and Proof env using the new fenced Div syntax. 
I did an update of the existing part, and added a sub section about how to convert from old to new syntax. This allow to keep a document of the old syntax but some things where removed (like the need of `echo = TRUE` on these chunk). Should we kept a subsection on this engine syntax ? 
I also added the option to deactivate insertion of default environment definition in preamble. 
At last, currently, we don't have support yet for EPUB or other formats so I tried to emphasized that. The
=> Document new custom environment syntax

R/utils.R, man/serve_book.Rd
`serve_book` docs have a small typo; they refer to `in_sesion` rather than `in_session`
=> Fix typo (in_sesion -> in_session)

DESCRIPTION, NEWS.md, R/bs4_book.R, inst/templates/bs4_book.html
Fix #1026
Well, unless there's a way to have math paragraphs in footnotes (since I didn't find a way to add those, I didn't test their rendering).
=> `bs4_book()`: Make math work in footnotes

DESCRIPTION, NEWS.md, R/bs4_book.R
Following part of the fix in https://github.com/r-lib/pkgdown/pull/1629/commits/3f4623f88b7e2f4f2a4c1fae61c30ccc88563ec7
This fix #1141
Issue was that indented text per https://bookdown.org/yihui/rmarkdown-cookbook/indent-text.html using Pandoc syntax Line Block (https://pandoc.org/MANUAL.html#line-blocks) have no `<p>` tag inside the `div` of class `line-block` created. We need to retrieve that explicitly
Tested in cderv/bs4booktesting repo
=> indented text should be part of search data for fuse.js in bs4_book

NEWS.md, inst/resources/bs4_book/bs4_book.css, inst/resources/bs4_book/bs4_book.js
@apreshill as discussed. 
I have used the same logic as Quarto, with icon built in (using inline svg). I have looked at the code there, and reuse part of it
I have kept the style of `bs4_book()` though, with the tooltip and background, and just change the text by an icon, which changes in click for a few seconds.
Example: https://cderv.github.io/bs4booktesting/icon-copy-btn/
We need to deal with the overlap discussed in #1187 (this PR could replace the other or complement only)
=> bs4_book: Copy button uses an icon instead of text

DESCRIPTION, NEWS.md, R/site.R, tests/testthat/helper-bs4_book.R, tests/testthat/helper.R, tests/testthat/test-site.R
fix #1194 
This just take into account possible comment at the end of the `site:` key line, and it adds some tests using testthat infra
=> Support comment after site: key in YAML header for index.Rmd

tests/testthat/test-site.R
Fix CI failure following afadf50. 
it seems a test working locally on Windows is not the same as in WINDOWS builder in GHA.
=> normalize path for comparaison in test

NEWS.md, inst/resources/bs4_book/bs4_book.js
This offer support for `collapse = FALSE` and deal with one of the feedback from #1040
This is also the behavior from `gitbook()`
Testing site: https://cderv.github.io/bs4booktesting/nocopybuttononoutput/#collapse-true-vs-false
Must follow #1187 that should be merged into master then this branch updated
=> only apply button to source code block

DESCRIPTION, NEWS.md, inst/resources/bs4_book/bs4_book.css, inst/resources/bs4_book/bs4_book.js
Fix #1086
Also related #1040 (currently the copy-code button might _hide_ some code)
=> bs4_book: no scroll on x overflow and correct copy btn placement

DESCRIPTION, NEWS.md, inst/resources/bs4_book/bs4_book.css, inst/resources/bs4_book/bs4_book.js
This reverts commit dc872256e297ee1ce8e451b42d65b53fc8e3720d (#1187) following discussion in #1040
Plan is to keep the scrolling but have the icon stays on the top right side even when scrolling. 
The button icon will always show so there could be overlap with long line as we no more wrapp. However, the icon is a lighter option than a button, and by default there is an opacity filter. It will be darker on button hover only.
Demo here: https://cderv.github.io/bs4booktesting/with-scroll/
=> Revert and improve change on code block regarding scrolling

R/bs4_book.R, man/bs4_book.Rd
cc @apreshill 
To do different tweak we think are necessary regarding what is possible for theming
Could still be changed with 
````yaml
bookdown::bs4_book:
theme:
version: 5
````
if a user really want to
=> Pin Boostrap version to 4 in bs4_book theme

NEWS.md, R/ebook.R, R/word.R
because pandoc will also generate these labels.
Fixes #1223.
=> Omit the figure and table labels for docx output from pandoc 2.14.1

NEWS.md, inst/resources/gitbook/css/plugin-bookdown.css, inst/templates/gitbook.html
Define styles in `#header .multi-author` instead. Fixes #1170.
=> Do not inline CSS in p.author when there are multiple authors

NEWS.md, R/html.R
also fix #902 and fix #1000.
I don't really remember why I required the .html filenames to be alphanumeric. After some testing, it seems that arbitrary characters work fine, so I'm removing this requirement.
=> Fix #605: allow non-alnum characters in .html filenames

DESCRIPTION, NEWS.md, inst/rmarkdown/lua/custom-environment.lua
This should fix #1233 and also https://github.com/yihui/tinytex/issues/324
A similar issue was also reported in French slack grrr where this was not working
````markdown
---
output:
bookdown::pdf_document2: 
keep_md: true
keep_tex: true
---
::: {.theorem}
Hello2
```{r}
1+1
```
:::
````
It ended up being a mistake when updating the code in #1145
=> Fix issue with Theorem Fenced div block in Lua filter

inst/rstudio/templates/project/resources/common/02-cross-refs.Rmd
Typo: `tag` instead of `tab` for tables cross references.
Thanks for your work!
=> Typo in template project 02-cross-refs.Rmd

DESCRIPTION, NEWS.md, R/bs4_book.R, man/bs4_book.Rd
I would love to tweak some of the elements in the bs4_book template.
The custom template feature is currently supported by gitbook but not by bs4_book.
This PR removes restrictions that barred bs4_book from accepting template argument.
=> Accept custom template for `bs4_book()`

NEWS.md, R/gitbook.R
so that extra_dependencies is not overridden by some Gitbook deps
This will close #1101
It should not be impactful and `extra_dependencies` must no be so used, and those who tried must have faced the issue. 
See discussion in #1101
Let's change the order.
=> Put gitbook dependencies before extra_dependencies

.github/workflows/R-CMD-check.yaml
This update the workflow to use last Pandoc version on Windows as this is now fix upstream.
=> Update GHA to using last Pandoc

DESCRIPTION, NEWS.md, R/utils.R
This PR closes #1285 by adding an option `bookdown.theorem.use` to opt out using the Lua filter `custom-environments.lua` to handle special environment supported by **bookdown**. Those described in https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#theorems
Option must be set to FALSE before running the function to render the document. 
Example: 
````
options(bookdown.theorem.use = FALSE)
rmarkdown::render("test.Rmd", bookdown::pdf_document2())
````
Option name maybe not be perfect. We alreary have an option `bookdown.theorem.preamble` that can be set to FALSE to prevent bookdown to include the LaTeX preamble itself. If you have another idea, happy to change the name.
=> Add an option to opt-out using custom environment lua filter

DESCRIPTION, NEWS.md, R/ebook.R, tests/testthat/_snaps/word/md-resolve-ref.md, tests/testthat/helper.R, tests/testthat/test-word.R
as this breaks our parsing process for section references.
This fixes #1301
THis PR is for now limited to the related issue but there are maybe other processing affected.
=> do not wrap HTML as it was done by default before Pandoc 2.17

DESCRIPTION, NEWS.md, R/gitbook.R, R/html.R, tests/testthat/helper.R, tests/testthat/test-gitbook.R, tests/testthat/test-html.R
Fixes #1327 and close #1326 by dealing with empty spans introduced in gitbook. 
basically for #1327 we had our usual regex issue following Pandoc 2.187 changes. There was the PART issue, but also the unnumbered chapter not being dealt with correctly. 
We did not detect sooner because we did not have tests for this. So I took the time to add some more test for this - took me a while to master more XPATH but that will be useful for further tests.
=> Fix TOC issues with pandoc 2.18 in gitbook()

DESCRIPTION, NEWS.md, inst/resources/bs4_book/bs4_book.css
Currently bookdown's `bs4_book()` output format doesn't apply any particular syntax highlighting to code tokens of class "import" and "built-in". This PR tries to remedy that by applying sensible styles to tokens of those classes.
Much of the background on this issue can be found at https://github.com/jgm/skylighting/issues/147, but in short:
Right now the imports in a Python code chunk don't have any visually distinguishing features. A statement like this:
```python
from plotnine import geom_text
```
appears like this, with no coloring or font weight changes:
```
from plotnine import geom_text
```
The reason this code doesn't get styled by `bs4_book.css` is that the CSS file doesn't actually *have* any extra styling information for those types of tokens (import tokens, specifically, but …
=> Add syntax highlighting for imports and built-ins tokens

DESCRIPTION, NEWS.md, inst/rmarkdown/lua/custom-environment.lua, tests/manual/theorem-proof-fenced.Rmd
This fixes #1371 and also make sure we handle other type of content like code chunk
````markdown
::: {#exr-1 .exercise}
1)  Open RStudio.
2)  Write `1 + 9` to console.
:::
::: {.exercise}
```r
library(knitr)
kable(mtcars)
```
Copy and paste the chunk above
:::
````
Adding `\leavevmode` was found in amsthm doc (http://www.ams.org/arc/tex/amscls/amsthdoc.pdf) - it is not the only way of doing it, but it seems to be required to correctly format the result in LaTeX. See explanation in the doc.
@yihui does it seems ok ? Do you think of other cases to test maybe ? I think the solution is general enough to support any usecase.
=> Fix Theorem / Proof environments with special markdown content

tests/testthat/helper-bs4_book.R
Since skip functions now return NULL.
=> Fix for dev testthat

NEWS.md, R/ebook.R
For you next release you are preparing @yihui
Closes #1416 
`--epub-chapter-level` is deprecated in favor of `--split-level` and throws a warning. We now use correct argument when pandoc 3 is used.
=> For pandoc 3.0+, use `--split-level`  when  `chapter_level` is passed in `epub_book`

DESCRIPTION, NEWS.md, R/bs4_book.R
=> fix: error on generating description from a long sentence

NEWS.md, inst/templates/bs4_book.html, inst/templates/gitbook.html
Not 100% sure, but based on a small amount of testing, I think this may render more neatly without sacrificing on portability or speed.
I noticed this when typesetting the formula for the sample standard deviation
`$$s=\sqrt{\frac1{n-1}\sum_{i=1}^n(x_i-\bar{x})^2}$$`
The default MathJax renderer of "Common HTML" "fakes" the square root top bar by using a border, which causes annoying misalignment with the radical symbol beside it. It also overall looks a bit more raggedy and not as pretty.
This small config change switches the default renderer to HTML+CSS (thanks @dennissxz for [the tip](https://github.com/jupyter-book/jupyter-book/issues/1174#issuecomment-759857170)).
Seems to be a marginal improvement.
=> Add config option to change MathJax renderer

R/bs4_book.R, R/html.R, R/skeleton.R, R/utils.R
The functions `knitr:::%n%` and `%||%` are identical, but `%||%` is in `base` and `%n%` is an internal function of the `knitr` package.
The R documentation states that using triple colon operator inside packages is typically a design mistake (https://stat.ethz.ch/R-manual/R-devel/library/base/html/ns-dblcolon.html) and in this case it can and should be avoided.
=> Change calls to `knitr:::%n%` to `%||%` as `%||%`  is a base function

NEWS.md, R/utils.R, inst/examples/01-introduction.Rmd, inst/examples/04-customization.Rmd, tests/testit/test-utils.R
Adds `include_md` option which toggles whether `.md` files are included in bookdown's search for source files. Default is not to include them soas not to introduce a breaking change.
=> Fix issue #956

.github/workflows/R-CMD-check.yaml, DESCRIPTION, tests/rmd/split-section.Rmd, tests/test-rmd.R, tests/testthat/helper-validate_html.R
=> Web API dependent HTML validation 
