rstudio/bookdown

R/render.R
Otherwise the "Knit" button in RStusio would not work.
=> add default param to output_format in render_book

R/html.R
=> Fix ordering of declaration of array variable.

R/render.R, man/render_book.Rd
@jjallaire Does this sound like a good idea?
=> close #69: add a clean_envir argument to clean the environment before rendering the book

inst/examples/01-components.Rmd
Thanks to #6 I was able to sort myself re: text-based links. Maybe you want to add this to the docs? I'm having trouble building that book, so you should check my links. But I have all of these forms working in a book that I can build, so I think I have them right.
=> document and demo text-based links

inst/examples/05-publishing.Rmd
I had hard time figuring out how to encode the GITHUB_PAT and making it work. I hope this make its clear for others.
=> Clarified description of PAT

inst/examples/02-components.Rmd
No major change - this is slightly more clear and concise IMO. Hope this is useful, many thanks for the package!
=> Minor rewrite of Chapter 2

R/html.R
=> Fixes parse_footnotes error when split by section issue #505

inst/resources/gitbook/js/plugin-sharing.js
Modified plugin-sharing.js to allow sharing of bookdown documents on LinkedIn
=> Added sharing for LinkedIn

README.md
* Note docs/book source: https://github.com/rstudio/bookdown/tree/master/inst/examples
* Link text https://bookdown.org/ update: remove "Get Started", note featured books
=> Small cleanup to README, last para: doc links.

inst/examples/03-formats.Rmd
Hi @yihui,
Stumbled upon a small typo.
Alison
=> fix typo instapper -> instapaper

R/gitbook.R, inst/templates/gitbook.html
- `link` tags need to be closed in XHTML (see https://www.w3schools.com/tags/tag_link.asp)
- `&` isn't a valid XML character on its own
=> fix 2 small XHTML output bugs

inst/examples/10-references.Rmd, inst/examples/krantz.cls, inst/examples/latex/after_body.tex
=> Correct running header in bibliography

inst/rstudio/templates/project/resources/README.md
There's no "Get Started" link on bookdown.org
=> provide more direct link to official bookdown book

NEWS.md, inst/resources/gitbook/js/plugin-sharing.js
=> Correctly encode twitter uri

DESCRIPTION, R/bs4_book.R, man/bs4_book.Rd
(To be merged after https://github.com/rstudio/bootstraplib/pull/150)
=> rename bootstraplib package to bslib

inst/templates/bs4_book.html
Related to #1016 as I was trying to add a quick tweak to my own book.
Or if all tweaks are supposed to be made via the theme argument, maybe the css argument of bs4_book (in the ... ) should be somehow coupled with warning message? (I realize forbidden might be too much as I use the css argument myself for print styles :grin:)
Cc @hadley
=> bs4_book: make it possible to override CSS?

inst/resources/bs4_book/bs4_book.css
=> h4 and h5 font-size in bs4_book

.github/workflows/R-CMD-check.yaml
* use pak
* use setup-tinytex v1
* Add test coverage
* change TMPDIR on windows
=> Improve GHA workflow

DESCRIPTION, NEWS.md, R/html.R, R/latex.R, inst/examples/02-components.Rmd, inst/rmarkdown/lua/custom-environment.lua
Fixes https://github.com/rstudio/bookdown/issues/1098
=> Add "Hypothesis" theorem environment

inst/examples/01-introduction.Rmd
Encouraging the use of the `remotes` package to install packages kept on github.
=> Change devtools for remotes

inst/templates/bs4_book.html
Not tested yet, opened just so I don't forget :slightly_smiling_face: 
Via https://github.com/r-lib/pkgdown/pull/1629#discussion_r621182057
=> Add integrity hashes to `bs4_book` external JS deps

DESCRIPTION, NEWS.md, inst/resources/bs4_book/bs4_book.css
Fix #1084 (if I understood the problem correctly)
=> `bs4_book()`: Fix alignment of text blocks within rmdnote divs

R/bs4_book.R, tests/testthat/test-bs4_book.R
=> Marked result of gsub as UTF-8 encoded

inst/examples/index.Rmd
(not all people/cultures might be familiar with this term)
=> [Book] Add link that explains 80/20 rule

DESCRIPTION, NEWS.md, R/bs4_book.R, inst/templates/bs4_book.html, man/bs4_book.Rd
- From https://github.com/rstudio/bookdown/issues/1146
=> Add split_bib to bs4_book

DESCRIPTION, NEWS.md, R/html.R
=> Skip data URLs when decoding URLs

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/workflows/pkgdown.yaml, DESCRIPTION, _pkgdown.yml, vignettes/articles/examples.yml
Using tidytemplate for R Markdown ecosystem (quillt like) and updating workflow to last r-lib/actions v2
=> Update pkgdown website and workflow

inst/examples/02-components.Rmd
Mentions the `imakeindex` package and some its options. Also, explain how to add subentries and show LaTeX code for adding a "see also" feature to the index.
=> Expand (LaTeX) index section

.github/workflows/R-CMD-check.yaml
as we wait for https://github.com/r-lib/actions/issues/868 to be fixed
=> [GHA] Fix pandoc devel action
